language: python
python:
  - 3.3
  - 3.5

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - python setup.py install

script:
  - nosetests

after_success:
  - pip install python-coveralls
